"""Cycle-2 experimental path. Does not replace the frozen v0.1.1 loop or Gate 1."""

from __future__ import annotations

CYCLE_ID = "C2"
SCHEMA_VERSION = "cycle2.1"
GATE1_LOCKED_RESULT = "FAIL"
GRAPH_STATUS = "GRAPH_PATH_PRESERVED"
GRAPH_EXPERIMENT = "GRAPH_EXPERIMENT_NOT_RUN_OUT_OF_SCOPE"
UNCERTAINTY_UNKNOWN = "UNCERTAINTY_UNKNOWN"
OPE_NOT_IDENTIFIABLE = "OPE_NOT_IDENTIFIABLE"

CLAIM_STATES = (
    "NOT_TESTED",
    "TESTED",
    "NOT_SUPPORTED",
    "PARTIALLY_SUPPORTED",
    "SUPPORTED_WITHIN_SCOPE",
    "REFUTED",
)

EVIDENCE_LEVELS = (
    "E0_IMPLEMENTED_ONLY",
    "E1_CONTROLLED_SYNTHETIC_MATCHED",
    "E2_CONTROLLED_SYNTHETIC_MISMATCHED",
    "E3_REAL_DATA_REPLAY",
    "E4_CONTROLLED_DEPLOYMENT_LIKE",
    "E5_LIVE_SHADOW_OBSERVATIONAL",
    "E6_CANARY_READY_NOT_DEPLOYED",
)

PROMOTION_STAGES = (
    "SHADOW",
    "COUNTERFACTUAL_EVALUATED",
    "OFFLINE_EXECUTABLE",
    "CANDIDATE",
    "CANARY_READY",
    "DEFAULT_ELIGIBLE",
)

RUN_ROLES = ("EXPLORATORY", "CONFIRMATORY", "DIAGNOSTIC", "REGRESSION")
